# Generated by Django 4.1.8 on 2023-10-07 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='id')),
                ('clave_unica', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=150, verbose_name='nombre')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=150, verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, db_column='fecha_inicio', verbose_name='fecha_inicio')),
                ('fecha_fin', models.DateTimeField(db_column='fecha_baja', default=None, null=True, verbose_name='fecha_baja')),
            ],
            options={
                'verbose_name': 'Grupos',
                'db_table': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='MotivoGrupo',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(db_column='nombre', max_length=150, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivos Grupo',
                'db_table': 'MotivosGrupo',
            },
        ),
    ]
