# Generated by Django 4.1.8 on 2023-10-08 02:29

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='grupo',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='clave_unica',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='grupo',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GrupoxUsuario',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='id')),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, db_column='fecha_inicio', verbose_name='fecha_inicio')),
                ('fecha_fin', models.DateTimeField(db_column='fecha_baja', default=None, null=True, verbose_name='fecha_baja')),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, default=0.0, max_digits=30)),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='grupos_usuario', to='grupos.grupo')),
            ],
            options={
                'verbose_name': 'GrupoxUsuario',
                'db_table': 'GrupoxUsuario',
            },
        ),
    ]
