# Generated by Django 4.2.6 on 2023-10-22 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0003_grupoxusuario_id_usuario'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='grupo',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='group_ptr',
        ),
        migrations.AddField(
            model_name='grupo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupoxusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grupoxusuario',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_grupos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motivogrupo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
