# Generated by Django 4.2.6 on 2023-10-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_cuenta_id_alter_cuenta_id_usuario_and_more'),
        ('grupos', '0004_alter_grupo_managers_remove_grupo_group_ptr_grupo_id_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
