# Generated by Django 4.1.8 on 2023-10-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(db_column='nombre', max_length=150, verbose_name='nombre')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=150, verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, db_column='fecha_alta', verbose_name='fecha_alta')),
                ('fecha_baja', models.DateTimeField(db_column='fecha_baja', default=None, null=True, verbose_name='fecha_baja')),
                ('fecha_ultima_modif', models.DateTimeField(db_column='fecha_ultima_modif', default=None, null=True, verbose_name='fecha_ultima_modif')),
                ('monto_actual', models.DecimalField(db_column='monto_actual', decimal_places=2, default=0.0, max_digits=30)),
            ],
            options={
                'verbose_name': 'Cuentas',
                'db_table': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(db_column='nombre', max_length=150, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipos Cuentas',
                'db_table': 'TiposCuenta',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, db_column='fecha_alta', verbose_name='fecha_alta')),
                ('fecha_baja', models.DateTimeField(db_column='fecha_baja', default=None, null=True, verbose_name='fecha_baja')),
                ('monto_movimiento', models.DecimalField(db_column='monto_movimiento', decimal_places=2, default=0.0, max_digits=30)),
                ('monto_cuenta', models.DecimalField(db_column='monto_cuenta', decimal_places=2, default=0.0, max_digits=30)),
                ('entrada', models.BooleanField(default=True)),
                ('id_cuenta', models.ForeignKey(db_column='id_cuenta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimientos_cuenta', to='cuentas.cuenta')),
            ],
            options={
                'verbose_name': 'Movimientos Cuenta',
                'db_table': 'MovimientosCuenta',
            },
        ),
    ]
