# Generated by Django 4.1.8 on 2023-10-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cuentas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimientos_usuario', to='usuarios.usuario'),
        ),
    ]
