# Generated by Django 4.1.8 on 2023-10-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimientos_cuenta', to='cuentas.tipocuenta'),
            preserve_default=False,
        ),
    ]
